In [80]:
import tensorflow as tf
import numpy as np
import pandas as pd
import os
import cv2
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

tf.compat.v1.disable_eager_execution()

In [81]:
flow_path = os.listdir('./datasets/flowers/')
flow_path

['daisy', 'dandelion', 'rose', 'sunflower', 'tulip']

In [82]:
path = './datasets/flowers/'

img_size = 64

image = []
label = []

for i in flow_path:
    data_path = path + str(i)
    fileName = [i for i in os.listdir(data_path) if i.endswith('jpg')]

    # print(fileName)

    for f in fileName:
        # reading the images
        img = cv2.imread(data_path + '/' + f)
        # pirnt(img)

        # resizing the images
        img = cv2.resize(img, (img_size, img_size))

        image.append(img)
        label.append(i)


In [83]:
image = np.array(image)
image = image.astype('float16') / 255

image

array([[[[0.545   , 0.5527  , 0.5527  ],
         [0.5884  , 0.5845  , 0.5845  ],
         [0.6     , 0.596   , 0.596   ],
         ...,
         [0.655   , 0.6353  , 0.639   ],
         [0.596   , 0.604   , 0.604   ],
         [0.6     , 0.6     , 0.6     ]],

        [[0.5137  , 0.533   , 0.537   ],
         [0.565   , 0.569   , 0.5728  ],
         [0.678   , 0.655   , 0.655   ],
         ...,
         [0.639   , 0.6196  , 0.6235  ],
         [0.6     , 0.608   , 0.608   ],
         [0.5845  , 0.5845  , 0.5845  ]],

        [[0.4626  , 0.4902  , 0.4941  ],
         [0.537   , 0.549   , 0.541   ],
         [0.604   , 0.604   , 0.604   ],
         ...,
         [0.612   , 0.612   , 0.612   ],
         [0.604   , 0.6157  , 0.6157  ],
         [0.5566  , 0.5605  , 0.565   ]],

        ...,

        [[0.0902  , 0.1726  , 0.1608  ],
         [0.098   , 0.1804  , 0.1686  ],
         [0.1412  , 0.2     , 0.1921  ],
         ...,
         [0.4785  , 0.4863  , 0.502   ],
         [0.4626  , 0.

In [84]:
image.shape

(4317, 64, 64, 3)

In [85]:

X = image
y = label

# change the labels to numeirc values
y_label_encoder = LabelEncoder()
y = y_label_encoder.fit_transform(y)

y

array([0, 0, 0, ..., 4, 4, 4], dtype=int64)

In [86]:
# oneHotEncodering the y

y = y.reshape(-1, 1)

onehotencoder = OneHotEncoder()

y = onehotencoder.fit_transform(y)

y = y.toarray()

y

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

In [87]:
X, y = shuffle(X, y, random_state=42)

In [88]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

In [89]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3453, 64, 64, 3), (864, 64, 64, 3), (3453, 5), (864, 5))

#### for processing we should change the shape of images to one dimensional arrays that why we multiply the (64, 64, 3) that it is equal to 12288

In [90]:
X_train = X_train.reshape(3453, 12288)

X_test = X_test.reshape(864, 12288)

In [91]:
X_train.shape, X_test.shape

((3453, 12288), (864, 12288))

In [107]:
lr = .001
epoch = 100
n_class = 5
n_dim = 64

x = tf.compat.v1.placeholder(tf.float16, [None, 12288])
w = tf.Variable(tf.cast(tf.zeros([12288, n_class]), tf.float16))
b = tf.Variable(tf.cast(tf.zeros([n_class]), tf.float16))
y_= tf.compat.v1.placeholder(tf.float16, [None, n_class])

init = tf.compat.v1.global_variables_initializer()


pred = tf.nn.softmax(tf.matmul(w, x) + b)


ValueError: Dimensions must be equal, but are 12288 and 5 for '{{node add_8}} = AddV2[T=DT_HALF](MatMul_8, add_8/ReadVariableOp)' with input shapes: [64,12288], [5].