In [38]:
import tensorflow as tf
import numpy as np
import pandas as pd
import os
import cv2
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

tf.compat.v1.disable_eager_execution()

In [39]:
flow_path = os.listdir('./datasets/flowers/')
flow_path

['daisy', 'dandelion', 'rose', 'sunflower', 'tulip']

In [40]:
path = './datasets/flowers/'

img_size = 64

image = []
label = []

for i in flow_path:
    data_path = path + str(i)
    fileName = [i for i in os.listdir(data_path) if i.endswith('jpg')]

    # print(fileName)

    for f in fileName:
        # reading the images
        img = cv2.imread(data_path + '/' + f)
        # pirnt(img)

        # resizing the images
        img = cv2.resize(img, (img_size, img_size))

        image.append(img)
        label.append(i)


In [41]:
image = np.array(image)
image = image.astype('float16') / 255

image

array([[[[0.545   , 0.5527  , 0.5527  ],
         [0.5884  , 0.5845  , 0.5845  ],
         [0.6     , 0.596   , 0.596   ],
         ...,
         [0.655   , 0.6353  , 0.639   ],
         [0.596   , 0.604   , 0.604   ],
         [0.6     , 0.6     , 0.6     ]],

        [[0.5137  , 0.533   , 0.537   ],
         [0.565   , 0.569   , 0.5728  ],
         [0.678   , 0.655   , 0.655   ],
         ...,
         [0.639   , 0.6196  , 0.6235  ],
         [0.6     , 0.608   , 0.608   ],
         [0.5845  , 0.5845  , 0.5845  ]],

        [[0.4626  , 0.4902  , 0.4941  ],
         [0.537   , 0.549   , 0.541   ],
         [0.604   , 0.604   , 0.604   ],
         ...,
         [0.612   , 0.612   , 0.612   ],
         [0.604   , 0.6157  , 0.6157  ],
         [0.5566  , 0.5605  , 0.565   ]],

        ...,

        [[0.0902  , 0.1726  , 0.1608  ],
         [0.098   , 0.1804  , 0.1686  ],
         [0.1412  , 0.2     , 0.1921  ],
         ...,
         [0.4785  , 0.4863  , 0.502   ],
         [0.4626  , 0.

In [42]:
image.shape

(4317, 64, 64, 3)

In [45]:

X = image
y = label

# change the labels to numeirc values
y_label_encoder = LabelEncoder()
y = y_label_encoder.fit_transform(y)

y

array([0, 0, 0, ..., 4, 4, 4], dtype=int64)

In [48]:
# oneHotEncodering the y

y = y.reshape(-1, 1)

onehotencoder = OneHotEncoder()

y = onehotencoder.fit_transform(y)

y = y.toarray()

y

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]])